theme: jekyll-theme-minimal
title: [Xinze (Alex) Li]
description: [lix2019@uchicago.edu]
logo: [https://d3qi0qp55mx5f5.cloudfront.net/cam/i/people/Graduate-Students/PhD/XinzeLi_2.jpg?mtime=1565894349]
